# Generated by Django 5.1.6 on 2025-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_property_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_plan',
            field=models.FileField(blank=True, null=True, upload_to='property-plan/'),
        ),
    ]
