# Generated by Django 5.1.6 on 2025-02-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_property_show_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-created_at',)},
        ),
    ]
