# Generated by Django 5.1.6 on 2025-02-25 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisitrequest',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
