# Generated by Django 5.1.6 on 2025-02-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_homevisitrequest_datetime_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_accress', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='models.property')),
            ],
        ),
    ]
