# Generated by Django 5.1.6 on 2025-02-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_homeaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeaccess',
            old_name='name_accress',
            new_name='name_access',
        ),
    ]
