# Generated by Django 5.1.6 on 2025-02-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_rename_name_accress_homeaccess_name_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentpost',
            options={'ordering': ('-created_at',), 'verbose_name': 'کامنت مقالات', 'verbose_name_plural': 'کامنت های مقالات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'دسته بندی مقالات', 'verbose_name_plural': 'دسته بندی های مقالات'},
        ),
    ]
