# Generated by Django 5.1.6 on 2025-02-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_commentpost_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name': 'دسته بندی امکانات', 'verbose_name_plural': 'دسته بندی های امکانات'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'کشور', 'verbose_name_plural': 'کشورها'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'امکانات', 'verbose_name_plural': 'امکانات'},
        ),
        migrations.AlterModelOptions(
            name='favoriteproperty',
            options={'verbose_name': 'آگهی نشان شده', 'verbose_name_plural': 'آگهی های نشان شده'},
        ),
        migrations.AlterModelOptions(
            name='homeaccess',
            options={'verbose_name': 'دسترسی خانه', 'verbose_name_plural': 'دسترسی های خانه ها'},
        ),
        migrations.AlterModelOptions(
            name='homevisitrequest',
            options={'verbose_name': 'درخواست بازدید خانه', 'verbose_name_plural': 'درخواست های بازدید خانه'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-created_at',), 'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی ها'},
        ),
        migrations.AlterModelOptions(
            name='propertycomment',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'کامنت اگهی', 'verbose_name_plural': 'کامنت های اگهی'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'عکس آگهی', 'verbose_name_plural': 'عکس های آگهی ها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
        migrations.AlterModelOptions(
            name='realstatecompany',
            options={'verbose_name': 'بنگاه املاک', 'verbose_name_plural': 'بنگاه های املاک'},
        ),
        migrations.AlterModelOptions(
            name='rentinfo',
            options={'verbose_name': 'آگهی اجاره', 'verbose_name_plural': 'آگهی های اجاره'},
        ),
        migrations.AlterModelOptions(
            name='saleinfo',
            options={'verbose_name': 'آگهی فروش', 'verbose_name_plural': 'آگهی های فروش'},
        ),
    ]
