# Generated by Django 5.1.6 on 2025-02-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_amenities_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('is_agent', 'has a real state company')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
