# Generated by Django 5.1.6 on 2025-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_property_house_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('villa', 'ویلا'), ('office', 'اداری'), ('apartman', 'آپارتمان'), ('house', 'خانه')], max_length=9)),
                ('transaction_type', models.CharField(choices=[('sale', 'برای فروش'), ('rent', 'برای اجاره')], max_length=10)),
                ('area', models.IntegerField()),
                ('land_area', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('num_garage', models.IntegerField()),
                ('land_garage', models.IntegerField()),
                ('year_construction', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
