# Generated by Django 5.1.6 on 2025-02-25 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_requestadvice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestadvice',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'درخواست مشاوره', 'verbose_name_plural': 'درخواست های مشاوره'},
        ),
        migrations.AddField(
            model_name='requestadvice',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
