# Generated by Django 5.1.6 on 2025-02-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='realstatecompany',
            name='avatar',
            field=models.ImageField(null=True, upload_to='company-avatars/'),
        ),
    ]
