# Generated by Django 5.1.6 on 2025-03-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_alter_homevisitrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestadvice',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
