# Generated by Django 5.1.6 on 2025-03-10 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_requestadvice_location_alter_requestadvice_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='garage_area',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='متراژ پارکینگ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='متراژ زمین'),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_bathrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=' تعداد حمام ها'),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_bedrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد اتاق خواب ها'),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_garage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد جای پارک ماشین'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_construction',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.validate_integer], verbose_name='سال ساخت'),
        ),
    ]
