# Generated by Django 5.1.6 on 2025-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_alter_property_garage_area_alter_property_house_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='garage_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num_garage',
        ),
        migrations.AddField(
            model_name='property',
            name='elevator',
            field=models.CharField(choices=[('d', 'دارد'), ('n', 'ندارد')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(choices=[('d', 'دارد'), ('n', 'ندارد')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='property',
            name='facilities',
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
