# Generated by Django 5.1.6 on 2025-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_remove_property_garage_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('sell', 'فروش'), ('rent', 'اجاره')], max_length=10, verbose_name='نوع معامله'),
        ),
    ]
