# Generated by Django 5.1.6 on 2025-03-10 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_construction',
            field=models.CharField(max_length=4, validators=[django.core.validators.validate_integer], verbose_name='سال ساخت'),
        ),
    ]
