# Generated by Django 5.1.6 on 2025-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_alter_property_year_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateRentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('v', 'ویلا'), ('o', 'اداری'), ('a', 'آپارتمان'), ('c', 'تجاری')], max_length=3)),
                ('location', models.CharField(max_length=255)),
                ('min_area', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('max_budget', models.IntegerField()),
                ('max_monthly_rent', models.IntegerField()),
                ('job', models.CharField(max_length=255)),
                ('num_family_members', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(choices=[('v', 'ویلا'), ('o', 'اداری'), ('a', 'آپارتمان'), ('c', 'تجاری')], max_length=1, null=True, verbose_name='نوع خانه'),
        ),
    ]
