# Generated by Django 5.1.6 on 2025-03-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_estaterentrequest_alter_property_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinfo',
            name='prepayment',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='پیشپرداخت (تومان)'),
        ),
    ]
